### ISSUE TITLE
Class 'App\Http\Controllers\Auth\SoapService' not found

### ISSUE THREAD

**Issue by kordhrufan** [czim/laravel-service#4]
Hi, this might be a silly question but I'm getting an error when I try to create a new SoapService

```
        // Instantiate service, with a to-array interpreter
        $service = new SoapService(
            $defaults,
            new \Czim\Service\Interpreters\BasicSoapXmlAsArrayInterpreter()
        );
```
why?

**Comment by czim** [comment]
Looks like a namespace problem. I assume you forgot to add a `use` import for the `SoapService`.
In this case, probably: `use Czim\Service\Services\SoapService;`...

**Comment by kordhrufan** [comment]
Oh yes it was that,, thank you so much!
